/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "on-primary-fixed": "#081b38",
        "inverse-primary": "#b6c7eb",
        secondary: "#6a5d43",
        "surface-container-low": "#f1f3ff",
        "surface-variant": "#d7e2ff",
        "surface-tint": "#4e5f7e",
        "surface-container-high": "#dfe8ff",
        "primary-fixed-dim": "#b6c7eb",
        "surface-dim": "#cadaff",
        "on-primary-container": "#8293b5",
        "on-secondary-container": "#6e6147",
        "secondary-container": "#f0debd",
        "on-secondary-fixed": "#231a06",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#454747",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-surface": "#081b38",
        "surface-container": "#e8eeff",
        "surface-container-highest": "#d7e2ff",
        "surface-bright": "#f9f9ff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "outline-variant": "#c5c6ce",
        "on-secondary": "#ffffff",
        tertiary: "#151717",
        "on-primary-fixed-variant": "#374765",
        "inverse-on-surface": "#ecf0ff",
        "tertiary-fixed": "#e2e2e2",
        outline: "#75777e",
        "on-secondary-fixed-variant": "#51452d",
        primary: "#031632",
        surface: "#f9f9ff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#d6c4a5",
        "tertiary-container": "#292b2b",
        "on-tertiary-container": "#919292",
        "on-background": "#081b38",
        "primary-fixed": "#d7e2ff",
        "inverse-surface": "#20304e",
        "on-tertiary-fixed": "#1a1c1c",
        "secondary-fixed": "#f3e0c0",
        "on-error": "#ffffff",
        "primary-container": "#1a2b48",
        "on-surface-variant": "#44474d",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Noto Serif", "serif"],
        label: ["Be Vietnam Pro", "sans-serif"]
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
    },
  },
  plugins: [],
};
